version: '3'
networks:
    app_net:
      driver: bridge
    prediccion_net:
      driver: bridge
services:
  predicciones:
    build: ./predicciones_f
    ports:
      - "5000:5000"
    environment:
      DB_NAME: monitor_predicciones
      DB_HOST: predicciones_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      predicciones_db:
        condition: service_healthy
    networks:
      - app_net
      - prediccion_net
  predicciones_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_predicciones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - prediccion_net
  predicciones_front:
    build: ./predicciones_front
    ports:
      - "3000:3000"
    networks:
      - app_net